export const rutas = {
  inicio: '/',
  catalogo: '/catalogo',
  categoria: (slug) => `/categoria/${slug}`,
  producto: (id) => `/producto/${id}`,
  carrito: '/carrito',
  checkout: '/checkout',
  checkoutResultado: '/checkout/resultado',
  recibo: (id) => `/recibo/${id}`,
  registro: '/registro',
  iniciarSesion: '/iniciar-sesion',
  quienesSomos: '/quienes-somos',
  contacto: '/contacto',
  perfil: '/perfil',
  vendedor: '/vendedor',
  vendedorInventario: '/vendedor/inventario',
  vendedorDevoluciones: '/vendedor/devoluciones',
  admin: '/admin',
  adminProductos: '/admin/productos',
  adminPedidos: '/admin/pedidos',
  adminMensajes: '/admin/mensajes',
  adminReportes: '/admin/reportes',
  adminUsuarios: '/admin/usuarios',
  adminBanners: '/admin/banners',
  adminDestacados: '/admin/destacados',
  adminPromociones: '/admin/promociones',
  adminCupones: '/admin/cupones',
  adminResenas: '/admin/resenas',
}
